-- Exemple (à adapter)
-- CREATE ROLE os_readonly LOGIN PASSWORD 'CHANGE_ME';
-- GRANT CONNECT ON DATABASE oceansentinel TO os_readonly;
-- GRANT USAGE ON SCHEMA public TO os_readonly;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO os_readonly;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO os_readonly;
